### ISSUE TITLE
Parsing the Json with Ssjs and Amp script code

### ISSUE THREAD

**Issue by SFMC100** [koldev/JsonParser#1]
I want to parse the JSON Input in AMPSCript code using Guide Template Language in Email Template. I have tried using AMPSCript code:

var @Json
set @Json = 
'{ 
"ArticleCount":22,
"Articles":[ 
{ 
"ArticleAbstractTeaser":null,
"ArticleActiveDate":null,
"Authors":[ 
{ 
"AuthorTypeId":1,
"CorrespondenceInformation":null
}
],
"Blurb":null,
"CmeUrls":[ 

],
"Links":[ 
{ 
"Description":null,
"LinkType":"jumplink"
},
{ 
"Description":null,
"LinkType":"figure"
},
{ 
"Description":"null",
"LinkType":"figure"
}
],
"Ordinal":0,
"PdfOnlyMessage":"",
"Topics":[ 
{ 
"Score":0,
"Topic":"ISSUE @ A GLANCE"
}
],
"UserHasAccess":false,
"VideoMultimediaUrlResponse":null
}
]
}'

{{.datasource JSONVar type=variable maxrows=20}}
{{.data}}
{ "target" : "@json" }
{{/data}}

ArticleCount: {{ArticleCount}}<br/>

{{.datasource Articles type=nested maxrows=20}}
{{.data}}
{ "target" : "JsonVar.Articles" }
{{/data}}

ArticleAbstractTeaser: {{ArticleAbstractTeaser}}<br/>
ArticleActiveDate: {{ArticleActiveDate}}<br/>

{{.datasource Authors type=nested maxrows=20}}
{{.data}}
{ "target" : "Articles.Authors" }
{{/data}}
{{/datasource}}

{{/datasource}}

{{/datasource}}
But it is not working, please anyone help me for JSON Parsing.

**Comment by koldev** [comment]
Please have a look at [json.org](http://json.org/) for JSON parser implementations.
