### ISSUE TITLE
Inconsistent parsing of arrays within json

### ISSUE THREAD

**Issue by vinrei** [koldev/JsonParser#3]
I am calling this library from Inno Setup 6.0.2
The following json string result in memory access violations for me:

`'{ "a": {"b": [ ] }, "d": "e"}'`

I was able to fix this by making the following changes to the `Value` function:

Line 287:
```
var
  N: Integer;
  O: TJsonObject;
  A: TJsonArray;
```

Line 324:
```
A := Array_(JsonParser, @Value);  
JsonParser.Output.Arrays[N] :=  A;  
```

Line 333:
```
O := Object_(JsonParser, @Value);
JsonParser.Output.Objects[N] := O;
```

@koldev Could you confirm this problem and fix?

**Comment by CCRDude** [comment]
I can confirm both bug (just experienced it myself, was looking for solutions) and fix here.

**Comment by koldev** [comment]
I fixed the bug. Thank you guys!
