### ISSUE TITLE
JsonParser.pas: Unrecognized parameter name "type" Compile aborted.

### ISSUE THREAD

**Issue by neciolaza** [koldev/JsonParser#5]
Hello, i'm trying to compile a test installer just to test processing of a json file, but while running the command "ISCC.exe json.example.installer.iss" i'm getting the error "JsonParser.pas: Unrecognized parameter name "type" Compile aborted." and i don´t know what exactly am i doing wrong. Not an expert on InnoSetup nor PascalScript. Can you point me to the right direction please?
[json.example.installer.iss.txt](https://github.com/koldev/JsonParser/files/9718157/json.example.installer.iss.txt)

**Comment by ChethanEJ7** [comment]
I see, #include ...JsonParser.pas is added in the file section, Please move it to Code section. It will work like a charm.! 

Tested..!!
